server:
  port: ${PORT:9001}
  servlet:
    contextPath: /producer

spring:
  profiles:
    active: ${ENV:prod}
  application:
    name: limpacity
  rabbitmq:
    host: ${RABBIT-HOST}
    port: ${RABBIT-PORT}
    username: ${RABBIT-USERNAME}
    password: ${RABBIT-PASSWORD}
    virtual-host: ${RABBIT-VHOST}
    events:
      solicitaColeta:
        exchange: ${MQ_EXCHANGE_COLETA}
        queueAguardando: ${MQ_COLETA_AGUARDANDO}
        queueEmail: ${MQ_COLETA_NOTIFICAR_EMAIL}

  security:
    user:
      name: ${SECURITY-USERNAME}
      password: ${SECURITY-PASSWORD}
security:
  jwt:
    uri: "/**"
    prefix: ${JWT_PREFIX}
    secret: ${JWT_SECRET}

info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

springdoc:
  version: '@project.version@'
  api-docs:
    groups:
      enabled: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false

timezone: ${TIMEZONE:America/Sao_Paulo}